name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - run: |
          set -e
          cargo test --lib
          cargo build --release
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          set -e
          cargo test --lib
          cargo build --release
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          set -e
          cargo test --lib
          cargo build --release
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          set -e
          cargo test --lib
          cargo build --release
